using namespace std;
//using namespace stdext;
#pragma warning(disable:4311)
#pragma warning(disable:4267)
#pragma warning(disable:4018)
#pragma warning(disable:4996)
#pragma warning(disable:4305)
#pragma warning(disable:4244)
#pragma warning(disable:4293)
#pragma warning(disable:4819)
#pragma warning(disable:4700)
#pragma warning(disable:4806)
#pragma warning(disable:4800)
#pragma warning(disable:4715)
#pragma warning(disable:4319)

class AccelerationStructure;
class BenchmarkTest;
class BitmapWriter;
class BoundingBox;
class BucketOrder;
class Camera;
class CameraLens;
class Color;
class Display;
class Filter;
class Geometry;
class GIEngine;
class ImageSampler;
class Instance;
class InstanceList;
class IntersectionState;
class LGAPI;
class LGAPIInterface;
class LightServer;
class LightSource;
class Matrix4;
class Modifier;
class Options;
class OrthoNormalBasis;
class Parser;
class ParameterList;
class PhotonStore;
class Point2;
class Point3;
class PrimitiveList;
class Ray;
class Scene;
class Shader;
class ShadingCache;
class ShadingState;
class Tesselatable;
class XYZColor;
class Vector3;